# Generated by Django 5.0.6 on 2024-06-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('product_name', models.CharField(max_length=400, verbose_name='Nombre del Producto')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion del Producto')),
                ('precio_original', models.IntegerField(default=0, verbose_name='Precio Original del Producto')),
                ('precio_actual', models.IntegerField(default=0, verbose_name='Precio Actual del Producto')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock restante del producto')),
                ('product_id', models.IntegerField(default='0', primary_key=True, serialize=False, verbose_name='Id del producto')),
                ('product_img', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Imagen del producto')),
            ],
        ),
    ]
